# Generated by Django 3.2.6 on 2021-09-12 08:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Transaction Amount')),
                ('Client_email', models.EmailField(max_length=254)),
                ('Client_first_name', models.CharField(max_length=100)),
                ('Client_last_name', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.order')),
            ],
            options={
                'ordering': ('-modified',),
            },
        ),
    ]
