# Generated by Django 3.2.8 on 2021-10-27 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shippmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippment_carrier', models.CharField(max_length=20)),
                ('shippment_service_carrier', models.CharField(max_length=255)),
                ('shippment_cost', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shippment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.shippmentoption'),
        ),
    ]
