# Generated by Django 3.2.6 on 2021-09-12 08:55

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_land', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Find_a_Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=250)),
                ('make', models.CharField(blank=True, max_length=250, null=True)),
                ('model', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.CharField(blank=True, max_length=250, null=True)),
                ('brand', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(blank=True, max_length=250, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_SKU', models.CharField(max_length=250, unique=True)),
                ('product_OEM', models.CharField(blank=True, max_length=250, null=True)),
                ('product_is_OEM', models.BooleanField(default=False)),
                ('product_photo_url', models.URLField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('product_short_description', models.TextField(blank=True, max_length=150, null=True)),
                ('product_description', models.TextField()),
                ('product_add_date', models.DateField(auto_now_add=True)),
                ('product_width', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('product_height', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('product_lenght', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('product_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='product_name', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_stock', models.IntegerField(blank=True, null=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.category')),
                ('product_find_part', models.ManyToManyField(to='Products.Find_a_Part')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
